### ISSUE TITLE
[FR] Add support for other Flickables - TVs, temperature, etc.

### ISSUE THREAD

**Issue by aph3rson** [NathanIkola/LightsOut#5]
While lights are the most power-hungry I've seen, there are some other elements which might not be useful while a room/building is empty, for example:

- TVs: pawns certainly aren't watching it while there's no one in the room.
- Heaters/coolers: for some types of building (e.g. a prison, guest house), I might not care what temperature it is while there's no one there.

It would be great if this mod had options to support those as well.

**Comment by NathanIkola** [comment]
TVs (and the Ideo speakers for that matter) differ greatly from workbenches and lights in a way that makes them difficult to work with. With workbenches I have the mod re-enable the bench when the pawn arrives to do a job, then disable it when they leave; with lights the presence of a pawn in the room is enough to say that the lights should be left on; with TVs they have multiple users (so the workbench strategy doesn't fit) and they have a defined area of effect (so the light strategy doesn't fit). I could _probably_ apply the light strategy to TVs, but it would be idiosyncratic behavior given how the TV operates in-game. I suppose I could see if there's a way to brute-force check if pawns are in the AoE of the TV, but I don't think that strategy works for the speakers et al.

How do you envision heaters/coolers working? They don't adjust room temperature very quickly, so it would only be workable in rooms where a pawn sits in for extended periods of time, so probably just bedrooms (the examples you gave) and workshops, right? Those are rooms that would be troublesome to not keep somewhat temperature-controlled even when pawns aren't in the room, particularly during extreme-temperature events like heat waves where getting the temperature to a comfortable level could take a while. It also gets complex really quickly because you'd have to take into consideration the behavior of vents (you'd want it to turn on when a pawn enters an adjacent, vented room as well as the room with the cooler itself).

Definitely open to suggestions. What are your thoughts?

**Comment by aph3rson** [comment]
> I could _probably_ apply the light strategy to TVs

This is mostly what I'd suggest, yeah. IMO, it makes sense for the TVs to be on while folks are still in the room (while not in the watch job), whereas it'd be great if they could be turned off if the room is empty. My hospital is currently the worst on this - every room has a TV, which sucks up 4KW of power when the hospital is empty.

> How do you envision heaters/coolers working?

Personally, I'd mostly use this for buildings that I don't expect to be occupied for some time. That'd include places like the hospital, the prison, and my guest building - they're only occupied on occasion, and it'd be a nice QoL improvement to not have to remember to turn the power back on.

**Comment by NathanIkola** [comment]
I wonder how easy it is to get the AoE bounds from a TV; if it's easy then I imagine it would be trivial to implement a brute force check of that range to see if it should be turned off when a pawn stops the watch job. It would only be 30 tiles to check, which wouldn't be that costly since it doesn't happen for more than a single tick at a time.

The other issue with heaters/coolers is that they don't lend themselves to how I've been modifying the game's behavior. I don't actually turn anything "off" with my mod per se. The benches are still active and functional (which is why pawns path to them still); I simply intercept the check for "how much power should this building draw" to tell the PowerNet that it doesn't draw any power. That would just cause heaters and coolers to continue heating/cooling, just without drawing power. I have to go an extra step with lights to disable the glower, but the game handles the rest of the logic once I do that (i.e. the logic for an area being "lit" is tied directly to the glower, so once I disable that it all works like an unpowered light in vanilla). From what I remember the temperature system isn't as convenient and would require more work to make functional. Then vents I don't even know how I'd deal with, since objects that are wall buildings/in-wall buildings are "part" of two rooms but can only actually belong to one of them in the game (it was a big problem with supporting WallLights originally). Plus it wouldn't just be one room over, I'd have to traverse all rooms connected by vents to see if there was a cooler in any of them that _may_ need to be turned on. I'd be doing that check any time a pawn entered a room, so that could quickly become infeasible as a solution.

If we abstract the problem into "areas of your base that don't get used often probably shouldn't draw power" does another solution jump out at you? I could see something like power districts or something, but that doesn't seem like a very UX-friendly concept, and I think it would perform poorly.

**Comment by NathanIkola** [comment]
Alright, all three vanilla televisions and the Ideo Loudspeaker are supported in this latest push. However, I also did a (fairly significant) refactor so I'm not going to push it to Steam until I can get some folks to trial run it to make sure nothing's broken. It all looks good on my side, but it wouldn't be the first time and it's not worth the headache for everyone involved.

Until a feasible solution comes up for the heaters/coolers thing I think I'm going to have to shelve it. I don't see that being a good/useful approach -- I think something more broad to address the issue would be a better solution in the long run, but I don't know what that would look like right now.
