### ISSUE TITLE
bug: Mech Gestator

### ISSUE THREAD

**Issue by Ulexus** [NathanIkola/LightsOut#6]
The new Mech Gestator, in v1.4 seems to be bugged, where it is stuck on standby even when there is a production queue.

**Comment by NathanIkola** [comment]
The Mech Gestator is new in Biotech, right? I don't have plans to buy Biotech, so I unfortunately don't have a way to troubleshoot this issue.

I suspect it's the kind of bench where a pawn gathers the supplies then the bench just churns out a product over time, right? If so, and if you (or anyone else reading this) are interested in helping out, I think looking at the [Androids compatibility patch](https://github.com/NathanIkola/LightsOut/tree/master/Source/LightsOutSln/LightsOut/Patches/ModCompatibility/Androids) as a template would be a good starting point.

Specifically we'd need a Biotech folder under ModCompatibility ([the same way as how Ideology is handled](https://github.com/NathanIkola/LightsOut/blob/master/Source/LightsOutSln/LightsOut/Patches/ModCompatibility/Ideology/IdeologyCompatibilityPatch.cs)), then a patch component that basically mimics [PatchDisablePowerDraw](https://github.com/NathanIkola/LightsOut/blob/master/Source/LightsOutSln/LightsOut/Patches/ModCompatibility/Androids/PatchDisablePowerDraw.cs)'s PrefixPatch except uses whatever system Tynan made for tracking that kind of bench. It looks like I don't change what the on/off dictionary says about the bench, I just use a prefix patch to override the behavior, so it will also be necessary to make a sister [PatchInspectMessage](https://github.com/NathanIkola/LightsOut/blob/master/Source/LightsOutSln/LightsOut/Patches/ModCompatibility/Androids/PatchInspectMessage.cs) patch component that makes it display correctly for those. Because it's already being picked up by my mod, there will be no need to replicate the PatchIsTable component that the Androids patch has.
